### ISSUE TITLE
Unable to start up

### ISSUE THREAD

**Issue by Chris-M** [johnpapa/heroes-vue#10]
C:\Users\User-PC\vue-learn\heroes-vue>npm --version
6.14.6

C:\Users\User-PC\vue-learn\heroes-vue>vue --version
@vue/cli 4.5.3

C:\Users\User-PC\vue-learn\heroes-vue>node --version
v12.18.3

C:\Users\User-PC\vue-learn\heroes-vue>npm install
```
npm WARN json-server-reset@1.3.0 requires a peer of json-server@^0.15 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1718 packages in 20.62s

48 packages are looking for funding
  run `npm fund` for details

found 416 vulnerabilities (397 low, 4 moderate, 15 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
---------

C:\Users\User-PC\vue-learn\heroes-vue>npm run quick
```
> heroes-vue@0.1.0 quick C:\Users\User-PC\vue-learn\heroes-vue
> concurrently "npm run backend" "npm run serve"

[1]
[1] > heroes-vue@0.1.0 serve C:\Users\User-PC\vue-learn\heroes-vue
[1] > vue-cli-service serve
.....

[1] <s> [webpack.Progress] 95% emitting
[1] <s> [webpack.Progress] 95% emitting HtmlWebpackPlugin
[1] <s> [webpack.Progress] 95% emitting CopyPlugin
[1] <s> [webpack.Progress] 98% after emitting
[1] <s> [webpack.Progress] 98% after emitting CopyPlugin
[1]  ERROR  Failed to compile with 1 errors07:32:42
[1]
[1]  error  in ./src/main.js
[1]
[1] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[1] Error: [BABEL] C:\Users\User-PC\vue-learn\heroes-vue\src\main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
[1] Require stack:
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\preset-env\lib\index.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@vue\babel-preset-app\index.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@vue\cli-plugin-babel\preset.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\core\lib\config\files\plugins.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\core\lib\config\files\index.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\core\lib\index.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@vue\cli-plugin-babel\index.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@vue\cli-service\lib\Service.js
[1] - C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@vue\cli-service\bin\vue-cli-service.js (While processing: "C:\\Users\\User-PC\\vue-learn\\heroes-vue\\node_modules\\@vue\\cli-plugin-babel\\preset.js")
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
[1]     at Module.require (internal/modules/cjs/loader.js:1025:19)
[1]     at require (internal/modules/cjs/helpers.js:72:18)
[1]     at Object.<anonymous> (C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
[1]     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[1]     at Module.load (internal/modules/cjs/loader.js:985:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
[1]     at Module.require (internal/modules/cjs/loader.js:1025:19)
[1]     at require (internal/modules/cjs/helpers.js:72:18)
[1]     at Object.<anonymous> (C:\Users\User-PC\vue-learn\heroes-vue\node_modules\@babel\preset-env\lib\index.js:29:44)
[1]     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[1]     at Module.load (internal/modules/cjs/loader.js:985:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
[1] <s> [webpack.Progress] 100%
[1]
[1]
[1]  @ multi (webpack)-dev-server/client?http://192.168.0.108:9626/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
[1]

```

**Comment by Chris-M** [comment]
FYI: Coming from the Pluralsight

**Comment by n0208385** [comment]
> FYI: Coming from the Pluralsight

I was able to fix this. run:

sudo npm update --depth 5 @babel/preset-env

then:

sudo npm update --depth 5 @babel/compat-data

then:

then npm run quick
